use_frameworks!

source 'https://github.com/jz709u/myCocoapodSpecs.git'

platform :ios, '10.0'

target 'testPod1_Example' do
  pod 'testPod1', :path => '../'

  target 'testPod1_Tests' do
    inherit! :search_paths

    
  end
end
